from PyQt5 import QtCore, QtGui, QtWidgets


class MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 40, 331, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_method = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_method.setObjectName("label_method")
        self.horizontalLayout_2.addWidget(self.label_method)
        self.combo_method = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_method.sizePolicy().hasHeightForWidth())
        self.combo_method.setSizePolicy(sizePolicy)
        self.combo_method.setObjectName("combo_method")
        self.combo_method.addItem("")
        self.combo_method.addItem("")
        self.combo_method.addItem("")
        self.horizontalLayout_2.addWidget(self.combo_method)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_model = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_model.setObjectName("label_model")
        self.horizontalLayout.addWidget(self.label_model)
        self.combo_model = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_model.sizePolicy().hasHeightForWidth())
        self.combo_model.setSizePolicy(sizePolicy)
        self.combo_model.setObjectName("combo_model")
        self.combo_model.addItem("")
        self.combo_model.addItem("")
        self.combo_model.addItem("")
        self.horizontalLayout.addWidget(self.combo_model)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_key = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_key.setObjectName("label_key")
        self.horizontalLayout_3.addWidget(self.label_key)
        self.edit_key = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_key.setObjectName("edit_key")
        self.horizontalLayout_3.addWidget(self.edit_key)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_vi = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_vi.setObjectName("label_vi")
        self.horizontalLayout_6.addWidget(self.label_vi)
        self.edit_vi = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_vi.setObjectName("edit_vi")
        self.horizontalLayout_6.addWidget(self.edit_vi)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(70, 220, 511, 121))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_src = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_src.setObjectName("label_src")
        self.horizontalLayout_5.addWidget(self.label_src)
        self.edit_src = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.edit_src.setObjectName("edit_src")
        self.horizontalLayout_5.addWidget(self.edit_src)
        self.btn_src = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btn_src.setObjectName("btn_src")
        self.horizontalLayout_5.addWidget(self.btn_src)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_dist = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_dist.setObjectName("label_dist")
        self.horizontalLayout_4.addWidget(self.label_dist)
        self.edit_dist = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.edit_dist.setObjectName("edit_dist")
        self.horizontalLayout_4.addWidget(self.edit_dist)
        self.btn_dist = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btn_dist.setObjectName("btn_dist")
        self.horizontalLayout_4.addWidget(self.btn_dist)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(640, 180, 131, 211))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_encrypt = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.verticalLayout_3.addWidget(self.btn_encrypt)
        self.btn_decrypt = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.verticalLayout_3.addWidget(self.btn_decrypt)
        self.btn_close = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout_3.addWidget(self.btn_close)
        self.line_top = QtWidgets.QFrame(self.centralwidget)
        self.line_top.setGeometry(QtCore.QRect(29, 12, 571, 16))
        self.line_top.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_top.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_top.setObjectName("line_top")
        self.line_bottom = QtWidgets.QFrame(self.centralwidget)
        self.line_bottom.setGeometry(QtCore.QRect(29, 570, 571, 20))
        self.line_bottom.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_bottom.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_bottom.setObjectName("line_bottom")
        self.line_left = QtWidgets.QFrame(self.centralwidget)
        self.line_left.setGeometry(QtCore.QRect(20, 20, 20, 560))
        self.line_left.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_left.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_left.setObjectName("line_left")
        self.line_center = QtWidgets.QFrame(self.centralwidget)
        self.line_center.setGeometry(QtCore.QRect(30, 170, 571, 16))
        self.line_center.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_center.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_center.setObjectName("line_center")
        self.line_right = QtWidgets.QFrame(self.centralwidget)
        self.line_right.setGeometry(QtCore.QRect(594, 19, 15, 561))
        self.line_right.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_right.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_right.setObjectName("line_right")
        self.label_tips = QtWidgets.QLabel(self.centralwidget)
        self.label_tips.setGeometry(QtCore.QRect(80, 380, 481, 161))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_tips.setFont(font)
        self.label_tips.setStyleSheet("border: 1px solid #c2c2c2;")
        self.label_tips.setTextFormat(QtCore.Qt.AutoText)
        self.label_tips.setIndent(-1)
        self.label_tips.setObjectName("label_tips")
        # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.combo_method, self.combo_model)
        MainWindow.setTabOrder(self.combo_model, self.edit_key)
        MainWindow.setTabOrder(self.edit_key, self.edit_vi)
        MainWindow.setTabOrder(self.edit_vi, self.edit_src)
        MainWindow.setTabOrder(self.edit_src, self.btn_src)
        MainWindow.setTabOrder(self.btn_src, self.edit_dist)
        MainWindow.setTabOrder(self.edit_dist, self.btn_dist)
        MainWindow.setTabOrder(self.btn_dist, self.btn_encrypt)
        MainWindow.setTabOrder(self.btn_encrypt, self.btn_decrypt)
        MainWindow.setTabOrder(self.btn_decrypt, self.btn_close)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文件加密"))
        self.label_method.setText(_translate("MainWindow", "加密算法："))
        self.combo_method.setItemText(0, _translate("MainWindow", "请选择"))
        self.combo_method.setItemText(1, _translate("MainWindow", "DES"))
        self.combo_method.setItemText(2, _translate("MainWindow", "AES"))
        self.label_model.setText(_translate("MainWindow", "加密模式："))
        self.combo_model.setItemText(0, _translate("MainWindow", "请选择"))
        self.combo_model.setItemText(1, _translate("MainWindow", "ECB"))
        self.combo_model.setItemText(2, _translate("MainWindow", "CBC"))
        self.label_key.setText(_translate("MainWindow", "加密密钥："))
        self.label_vi.setText(_translate("MainWindow", "偏 移 量："))
        self.label_src.setText(_translate("MainWindow", "输入路径："))
        self.btn_src.setText(_translate("MainWindow", "..."))
        self.label_dist.setText(_translate("MainWindow", "输出路径："))
        self.btn_dist.setText(_translate("MainWindow", "..."))
        self.btn_encrypt.setText(_translate("MainWindow", "加 密"))
        self.btn_decrypt.setText(_translate("MainWindow", "解 密"))
        self.btn_close.setText(_translate("MainWindow", "退 出"))
        self.label_tips.setText(_translate("MainWindow", "Tips\n""\n"
                                                         "输入路径为要加密的文件\n"
                                                         "输出路径为加密后文件的存储位置\n""\n"
                                                         "DES加密密钥为8位，CBC模式下偏移量为8位\n"
                                                         "AES加密密钥位16/24/32位，CBC模式下偏移量长度为16位"))
